# Exported from Render on 2026-04-12T04:01:48Z
version: "1"
services:
- type: web
  name: neolabcare
  runtime: static
  repo: https://github.com/lareesahu/neolab-landing
  branch: master
  autoDeploy: true
  staticPublishPath: .
